version = 1

[formatters]

    [formatters.f]
    format = "%(asctime)s %(name)-12s %(levelname)-8s %(message)s"

[handlers]

    [handlers.h]
    class = "logging.StreamHandler" # console
    formatter = "f"
    level = 10 # logging.DEBUG

[root]
    handlers = "h"
    level = 10 # standard, may be overwritten by definitions in handlers
